sudo: required
services:
  - docker

before_install:
  - docker build -t penguinairlines/learn-kubernetes-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true penguinairlines/learn-kubernetes-ci npm run test
language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Environments"
  env: "LearnKubernetesCi-env"
  bucket_name: "elasticbeanstalk-us-east-1-207336598549"
  bucket_path: "Environments"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
